import { MigrationInterface, QueryRunner } from "typeorm";

export class RenameMaterialToChemical1731639831462 implements MigrationInterface {
    name = 'RenameMaterialToChemical1731639831462'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "temporary_sample" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "description" varchar NOT NULL, "form" varchar NOT NULL, "source" varchar NOT NULL, "note" varchar NOT NULL, "attachments" json NOT NULL, "images" json NOT NULL, "create_at" datetime NOT NULL DEFAULT (datetime('now')), "update_at" datetime DEFAULT (datetime('now')), "materialId" varchar, "categoryId" varchar, "organizationId" varchar, CONSTRAINT "UQ_7c453dce19d37ae0e4ecbd10709" UNIQUE ("name"), CONSTRAINT "FK_885ee312ba08566765412f5c246" FOREIGN KEY ("categoryId") REFERENCES "category" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_9855ae6df5fcd0db02a2eb33104" FOREIGN KEY ("organizationId") REFERENCES "organization" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_sample"("id", "name", "description", "form", "source", "note", "attachments", "images", "create_at", "update_at", "materialId", "categoryId", "organizationId") SELECT "id", "name", "description", "form", "source", "note", "attachments", "images", "create_at", "update_at", "materialId", "categoryId", "organizationId" FROM "sample"`);
        await queryRunner.query(`DROP TABLE "sample"`);
        await queryRunner.query(`ALTER TABLE "temporary_sample" RENAME TO "sample"`);
        await queryRunner.query(`CREATE TABLE "chemical" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "description" varchar NOT NULL, CONSTRAINT "UQ_b0978d04fd0a03ca93abb0c610a" UNIQUE ("name"))`);
        await queryRunner.query(`CREATE TABLE "temporary_sample" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "description" varchar NOT NULL, "form" varchar NOT NULL, "source" varchar NOT NULL, "note" varchar NOT NULL, "attachments" json NOT NULL, "images" json NOT NULL, "create_at" datetime NOT NULL DEFAULT (datetime('now')), "update_at" datetime DEFAULT (datetime('now')), "materialId" varchar, "categoryId" varchar, "organizationId" varchar, CONSTRAINT "UQ_7c453dce19d37ae0e4ecbd10709" UNIQUE ("name"))`);
        await queryRunner.query(`INSERT INTO "temporary_sample"("id", "name", "description", "form", "source", "note", "attachments", "images", "create_at", "update_at", "materialId", "categoryId", "organizationId") SELECT "id", "name", "description", "form", "source", "note", "attachments", "images", "create_at", "update_at", "materialId", "categoryId", "organizationId" FROM "sample"`);
        await queryRunner.query(`DROP TABLE "sample"`);
        await queryRunner.query(`ALTER TABLE "temporary_sample" RENAME TO "sample"`);
        await queryRunner.query(`CREATE TABLE "temporary_sample" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "description" varchar NOT NULL, "form" varchar NOT NULL, "source" varchar NOT NULL, "note" varchar NOT NULL, "attachments" json NOT NULL, "images" json NOT NULL, "create_at" datetime NOT NULL DEFAULT (datetime('now')), "update_at" datetime DEFAULT (datetime('now')), "materialId" varchar NOT NULL, "categoryId" varchar, "organizationId" varchar NOT NULL, CONSTRAINT "UQ_7c453dce19d37ae0e4ecbd10709" UNIQUE ("name"))`);
        await queryRunner.query(`INSERT INTO "temporary_sample"("id", "name", "description", "form", "source", "note", "attachments", "images", "create_at", "update_at", "materialId", "categoryId", "organizationId") SELECT "id", "name", "description", "form", "source", "note", "attachments", "images", "create_at", "update_at", "materialId", "categoryId", "organizationId" FROM "sample"`);
        await queryRunner.query(`DROP TABLE "sample"`);
        await queryRunner.query(`ALTER TABLE "temporary_sample" RENAME TO "sample"`);
        await queryRunner.query(`CREATE TABLE "temporary_sample" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "description" varchar NOT NULL, "form" varchar NOT NULL, "source" varchar NOT NULL, "note" varchar NOT NULL, "attachments" json NOT NULL, "images" json NOT NULL, "create_at" datetime NOT NULL DEFAULT (datetime('now')), "update_at" datetime DEFAULT (datetime('now')), "materialId" varchar NOT NULL, "categoryId" varchar, "organizationId" varchar NOT NULL, CONSTRAINT "UQ_7c453dce19d37ae0e4ecbd10709" UNIQUE ("name"), CONSTRAINT "FK_0fb44e2a6abc57477a30b93629e" FOREIGN KEY ("materialId") REFERENCES "chemical" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_885ee312ba08566765412f5c246" FOREIGN KEY ("categoryId") REFERENCES "category" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_9855ae6df5fcd0db02a2eb33104" FOREIGN KEY ("organizationId") REFERENCES "organization" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_sample"("id", "name", "description", "form", "source", "note", "attachments", "images", "create_at", "update_at", "materialId", "categoryId", "organizationId") SELECT "id", "name", "description", "form", "source", "note", "attachments", "images", "create_at", "update_at", "materialId", "categoryId", "organizationId" FROM "sample"`);
        await queryRunner.query(`DROP TABLE "sample"`);
        await queryRunner.query(`ALTER TABLE "temporary_sample" RENAME TO "sample"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "sample" RENAME TO "temporary_sample"`);
        await queryRunner.query(`CREATE TABLE "sample" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "description" varchar NOT NULL, "form" varchar NOT NULL, "source" varchar NOT NULL, "note" varchar NOT NULL, "attachments" json NOT NULL, "images" json NOT NULL, "create_at" datetime NOT NULL DEFAULT (datetime('now')), "update_at" datetime DEFAULT (datetime('now')), "materialId" varchar NOT NULL, "categoryId" varchar, "organizationId" varchar NOT NULL, CONSTRAINT "UQ_7c453dce19d37ae0e4ecbd10709" UNIQUE ("name"))`);
        await queryRunner.query(`INSERT INTO "sample"("id", "name", "description", "form", "source", "note", "attachments", "images", "create_at", "update_at", "materialId", "categoryId", "organizationId") SELECT "id", "name", "description", "form", "source", "note", "attachments", "images", "create_at", "update_at", "materialId", "categoryId", "organizationId" FROM "temporary_sample"`);
        await queryRunner.query(`DROP TABLE "temporary_sample"`);
        await queryRunner.query(`ALTER TABLE "sample" RENAME TO "temporary_sample"`);
        await queryRunner.query(`CREATE TABLE "sample" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "description" varchar NOT NULL, "form" varchar NOT NULL, "source" varchar NOT NULL, "note" varchar NOT NULL, "attachments" json NOT NULL, "images" json NOT NULL, "create_at" datetime NOT NULL DEFAULT (datetime('now')), "update_at" datetime DEFAULT (datetime('now')), "materialId" varchar, "categoryId" varchar, "organizationId" varchar, CONSTRAINT "UQ_7c453dce19d37ae0e4ecbd10709" UNIQUE ("name"))`);
        await queryRunner.query(`INSERT INTO "sample"("id", "name", "description", "form", "source", "note", "attachments", "images", "create_at", "update_at", "materialId", "categoryId", "organizationId") SELECT "id", "name", "description", "form", "source", "note", "attachments", "images", "create_at", "update_at", "materialId", "categoryId", "organizationId" FROM "temporary_sample"`);
        await queryRunner.query(`DROP TABLE "temporary_sample"`);
        await queryRunner.query(`ALTER TABLE "sample" RENAME TO "temporary_sample"`);
        await queryRunner.query(`CREATE TABLE "sample" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "description" varchar NOT NULL, "form" varchar NOT NULL, "source" varchar NOT NULL, "note" varchar NOT NULL, "attachments" json NOT NULL, "images" json NOT NULL, "create_at" datetime NOT NULL DEFAULT (datetime('now')), "update_at" datetime DEFAULT (datetime('now')), "materialId" varchar, "categoryId" varchar, "organizationId" varchar, CONSTRAINT "UQ_7c453dce19d37ae0e4ecbd10709" UNIQUE ("name"), CONSTRAINT "FK_9855ae6df5fcd0db02a2eb33104" FOREIGN KEY ("organizationId") REFERENCES "organization" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "sample"("id", "name", "description", "form", "source", "note", "attachments", "images", "create_at", "update_at", "materialId", "categoryId", "organizationId") SELECT "id", "name", "description", "form", "source", "note", "attachments", "images", "create_at", "update_at", "materialId", "categoryId", "organizationId" FROM "temporary_sample"`);
        await queryRunner.query(`DROP TABLE "temporary_sample"`);
        await queryRunner.query(`DROP TABLE "chemical"`);
        await queryRunner.query(`ALTER TABLE "sample" RENAME TO "temporary_sample"`);
        await queryRunner.query(`CREATE TABLE "sample" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "description" varchar NOT NULL, "form" varchar NOT NULL, "source" varchar NOT NULL, "note" varchar NOT NULL, "attachments" json NOT NULL, "images" json NOT NULL, "create_at" datetime NOT NULL DEFAULT (datetime('now')), "update_at" datetime DEFAULT (datetime('now')), "materialId" varchar, "categoryId" varchar, "organizationId" varchar, CONSTRAINT "UQ_7c453dce19d37ae0e4ecbd10709" UNIQUE ("name"), CONSTRAINT "FK_0fb44e2a6abc57477a30b93629e" FOREIGN KEY ("materialId") REFERENCES "material" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_885ee312ba08566765412f5c246" FOREIGN KEY ("categoryId") REFERENCES "category" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_9855ae6df5fcd0db02a2eb33104" FOREIGN KEY ("organizationId") REFERENCES "organization" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "sample"("id", "name", "description", "form", "source", "note", "attachments", "images", "create_at", "update_at", "materialId", "categoryId", "organizationId") SELECT "id", "name", "description", "form", "source", "note", "attachments", "images", "create_at", "update_at", "materialId", "categoryId", "organizationId" FROM "temporary_sample"`);
        await queryRunner.query(`DROP TABLE "temporary_sample"`);
    }

}
