import { MigrationInterface, QueryRunner } from "typeorm";

export class Measurement1734491976405 implements MigrationInterface {
    name = 'Measurement1734491976405'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "temporary_measurement" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "measurementRange" varchar, "typeData" varchar, "measurementConditionAccumulations" integer NOT NULL, "measurementConditionWavelength" varchar, "measurementConditionSource" varchar, "measurementConditionBeamsplitter" varchar, "measurementConditionDetector" varchar, "measurementConditionLaserpower" varchar, "measurementConditionExposuretime" varchar, "measurementConditionLens" varchar, "measurementTechniqueSersChip" varchar NOT NULL, "measurementTechniqueSersNanoparticles" varchar NOT NULL, "measurementTechniqueSersPapers" varchar NOT NULL, "measurementTechniqueSersOther" varchar NOT NULL, "experimentId" varchar, CONSTRAINT "FK_6b6e4936818d76b783b18ff5ac6" FOREIGN KEY ("experimentId") REFERENCES "experiment" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_measurement"("id", "name", "measurementRange", "typeData", "measurementConditionAccumulations", "measurementConditionWavelength", "measurementConditionSource", "measurementConditionBeamsplitter", "measurementConditionDetector", "measurementConditionLaserpower", "measurementConditionExposuretime", "measurementConditionLens", "measurementTechniqueSersChip", "measurementTechniqueSersNanoparticles", "measurementTechniqueSersPapers", "measurementTechniqueSersOther", "experimentId") SELECT "id", "name", "measurementRange", "typeData", "measurementConditionAccumulations", "measurementConditionWavelength", "measurementConditionSource", "measurementConditionBeamsplitter", "measurementConditionDetector", "measurementConditionLaserpower", "measurementConditionExposuretime", "measurementConditionLens", "measurementTechniqueSersChip", "measurementTechniqueSersNanoparticles", "measurementTechniqueSersPapers", "measurementTechniqueSersOther", "experimentId" FROM "measurement"`);
        await queryRunner.query(`DROP TABLE "measurement"`);
        await queryRunner.query(`ALTER TABLE "temporary_measurement" RENAME TO "measurement"`);
        await queryRunner.query(`CREATE TABLE "temporary_measurement" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "measurementRange" varchar, "typeData" varchar, "measurementConditionAccumulations" integer NOT NULL, "measurementConditionWavelength" varchar, "measurementConditionSource" varchar, "measurementConditionBeamsplitter" varchar, "measurementConditionDetector" varchar, "measurementConditionLaserpower" varchar, "measurementConditionExposuretime" varchar, "measurementConditionLens" varchar, "measurementTechniqueSersChip" varchar NOT NULL, "measurementTechniqueSersNanoparticles" varchar NOT NULL, "measurementTechniqueSersPapers" varchar NOT NULL, "measurementTechniqueSersOther" varchar NOT NULL, "experimentId" varchar, "attachmentName" varchar NOT NULL, "attachmentSize" integer NOT NULL, "attachmentMimetype" varchar NOT NULL, "attachmentFileext" varchar NOT NULL, CONSTRAINT "FK_6b6e4936818d76b783b18ff5ac6" FOREIGN KEY ("experimentId") REFERENCES "experiment" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_measurement"("id", "name", "measurementRange", "typeData", "measurementConditionAccumulations", "measurementConditionWavelength", "measurementConditionSource", "measurementConditionBeamsplitter", "measurementConditionDetector", "measurementConditionLaserpower", "measurementConditionExposuretime", "measurementConditionLens", "measurementTechniqueSersChip", "measurementTechniqueSersNanoparticles", "measurementTechniqueSersPapers", "measurementTechniqueSersOther", "experimentId") SELECT "id", "name", "measurementRange", "typeData", "measurementConditionAccumulations", "measurementConditionWavelength", "measurementConditionSource", "measurementConditionBeamsplitter", "measurementConditionDetector", "measurementConditionLaserpower", "measurementConditionExposuretime", "measurementConditionLens", "measurementTechniqueSersChip", "measurementTechniqueSersNanoparticles", "measurementTechniqueSersPapers", "measurementTechniqueSersOther", "experimentId" FROM "measurement"`);
        await queryRunner.query(`DROP TABLE "measurement"`);
        await queryRunner.query(`ALTER TABLE "temporary_measurement" RENAME TO "measurement"`);
        await queryRunner.query(`CREATE TABLE "temporary_measurement" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "measurementRange" varchar, "typeData" varchar, "measurementConditionAccumulations" integer NOT NULL, "measurementConditionWavelength" varchar, "measurementConditionSource" varchar, "measurementConditionBeamsplitter" varchar, "measurementConditionDetector" varchar, "measurementConditionLaserpower" varchar, "measurementConditionExposuretime" varchar, "measurementConditionLens" varchar, "measurementTechniqueSersChip" varchar, "measurementTechniqueSersNanoparticles" varchar, "measurementTechniqueSersPapers" varchar, "measurementTechniqueSersOther" varchar, "experimentId" varchar, "attachmentName" varchar NOT NULL, "attachmentSize" integer NOT NULL, "attachmentMimetype" varchar NOT NULL, "attachmentFileext" varchar NOT NULL, CONSTRAINT "FK_6b6e4936818d76b783b18ff5ac6" FOREIGN KEY ("experimentId") REFERENCES "experiment" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_measurement"("id", "name", "measurementRange", "typeData", "measurementConditionAccumulations", "measurementConditionWavelength", "measurementConditionSource", "measurementConditionBeamsplitter", "measurementConditionDetector", "measurementConditionLaserpower", "measurementConditionExposuretime", "measurementConditionLens", "measurementTechniqueSersChip", "measurementTechniqueSersNanoparticles", "measurementTechniqueSersPapers", "measurementTechniqueSersOther", "experimentId", "attachmentName", "attachmentSize", "attachmentMimetype", "attachmentFileext") SELECT "id", "name", "measurementRange", "typeData", "measurementConditionAccumulations", "measurementConditionWavelength", "measurementConditionSource", "measurementConditionBeamsplitter", "measurementConditionDetector", "measurementConditionLaserpower", "measurementConditionExposuretime", "measurementConditionLens", "measurementTechniqueSersChip", "measurementTechniqueSersNanoparticles", "measurementTechniqueSersPapers", "measurementTechniqueSersOther", "experimentId", "attachmentName", "attachmentSize", "attachmentMimetype", "attachmentFileext" FROM "measurement"`);
        await queryRunner.query(`DROP TABLE "measurement"`);
        await queryRunner.query(`ALTER TABLE "temporary_measurement" RENAME TO "measurement"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "measurement" RENAME TO "temporary_measurement"`);
        await queryRunner.query(`CREATE TABLE "measurement" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "measurementRange" varchar, "typeData" varchar, "measurementConditionAccumulations" integer NOT NULL, "measurementConditionWavelength" varchar, "measurementConditionSource" varchar, "measurementConditionBeamsplitter" varchar, "measurementConditionDetector" varchar, "measurementConditionLaserpower" varchar, "measurementConditionExposuretime" varchar, "measurementConditionLens" varchar, "measurementTechniqueSersChip" varchar NOT NULL, "measurementTechniqueSersNanoparticles" varchar NOT NULL, "measurementTechniqueSersPapers" varchar NOT NULL, "measurementTechniqueSersOther" varchar NOT NULL, "experimentId" varchar, "attachmentName" varchar NOT NULL, "attachmentSize" integer NOT NULL, "attachmentMimetype" varchar NOT NULL, "attachmentFileext" varchar NOT NULL, CONSTRAINT "FK_6b6e4936818d76b783b18ff5ac6" FOREIGN KEY ("experimentId") REFERENCES "experiment" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "measurement"("id", "name", "measurementRange", "typeData", "measurementConditionAccumulations", "measurementConditionWavelength", "measurementConditionSource", "measurementConditionBeamsplitter", "measurementConditionDetector", "measurementConditionLaserpower", "measurementConditionExposuretime", "measurementConditionLens", "measurementTechniqueSersChip", "measurementTechniqueSersNanoparticles", "measurementTechniqueSersPapers", "measurementTechniqueSersOther", "experimentId", "attachmentName", "attachmentSize", "attachmentMimetype", "attachmentFileext") SELECT "id", "name", "measurementRange", "typeData", "measurementConditionAccumulations", "measurementConditionWavelength", "measurementConditionSource", "measurementConditionBeamsplitter", "measurementConditionDetector", "measurementConditionLaserpower", "measurementConditionExposuretime", "measurementConditionLens", "measurementTechniqueSersChip", "measurementTechniqueSersNanoparticles", "measurementTechniqueSersPapers", "measurementTechniqueSersOther", "experimentId", "attachmentName", "attachmentSize", "attachmentMimetype", "attachmentFileext" FROM "temporary_measurement"`);
        await queryRunner.query(`DROP TABLE "temporary_measurement"`);
        await queryRunner.query(`ALTER TABLE "measurement" RENAME TO "temporary_measurement"`);
        await queryRunner.query(`CREATE TABLE "measurement" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "measurementRange" varchar, "typeData" varchar, "measurementConditionAccumulations" integer NOT NULL, "measurementConditionWavelength" varchar, "measurementConditionSource" varchar, "measurementConditionBeamsplitter" varchar, "measurementConditionDetector" varchar, "measurementConditionLaserpower" varchar, "measurementConditionExposuretime" varchar, "measurementConditionLens" varchar, "measurementTechniqueSersChip" varchar NOT NULL, "measurementTechniqueSersNanoparticles" varchar NOT NULL, "measurementTechniqueSersPapers" varchar NOT NULL, "measurementTechniqueSersOther" varchar NOT NULL, "experimentId" varchar, CONSTRAINT "FK_6b6e4936818d76b783b18ff5ac6" FOREIGN KEY ("experimentId") REFERENCES "experiment" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "measurement"("id", "name", "measurementRange", "typeData", "measurementConditionAccumulations", "measurementConditionWavelength", "measurementConditionSource", "measurementConditionBeamsplitter", "measurementConditionDetector", "measurementConditionLaserpower", "measurementConditionExposuretime", "measurementConditionLens", "measurementTechniqueSersChip", "measurementTechniqueSersNanoparticles", "measurementTechniqueSersPapers", "measurementTechniqueSersOther", "experimentId") SELECT "id", "name", "measurementRange", "typeData", "measurementConditionAccumulations", "measurementConditionWavelength", "measurementConditionSource", "measurementConditionBeamsplitter", "measurementConditionDetector", "measurementConditionLaserpower", "measurementConditionExposuretime", "measurementConditionLens", "measurementTechniqueSersChip", "measurementTechniqueSersNanoparticles", "measurementTechniqueSersPapers", "measurementTechniqueSersOther", "experimentId" FROM "temporary_measurement"`);
        await queryRunner.query(`DROP TABLE "temporary_measurement"`);
        await queryRunner.query(`ALTER TABLE "measurement" RENAME TO "temporary_measurement"`);
        await queryRunner.query(`CREATE TABLE "measurement" ("id" varchar PRIMARY KEY NOT NULL, "files" json, "name" varchar NOT NULL, "measurementRange" varchar, "typeData" varchar, "measurementConditionAccumulations" integer NOT NULL, "measurementConditionWavelength" varchar, "measurementConditionSource" varchar, "measurementConditionBeamsplitter" varchar, "measurementConditionDetector" varchar, "measurementConditionLaserpower" varchar, "measurementConditionExposuretime" varchar, "measurementConditionLens" varchar, "measurementTechniqueSersChip" varchar NOT NULL, "measurementTechniqueSersNanoparticles" varchar NOT NULL, "measurementTechniqueSersPapers" varchar NOT NULL, "measurementTechniqueSersOther" varchar NOT NULL, "experimentId" varchar, CONSTRAINT "FK_6b6e4936818d76b783b18ff5ac6" FOREIGN KEY ("experimentId") REFERENCES "experiment" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "measurement"("id", "name", "measurementRange", "typeData", "measurementConditionAccumulations", "measurementConditionWavelength", "measurementConditionSource", "measurementConditionBeamsplitter", "measurementConditionDetector", "measurementConditionLaserpower", "measurementConditionExposuretime", "measurementConditionLens", "measurementTechniqueSersChip", "measurementTechniqueSersNanoparticles", "measurementTechniqueSersPapers", "measurementTechniqueSersOther", "experimentId") SELECT "id", "name", "measurementRange", "typeData", "measurementConditionAccumulations", "measurementConditionWavelength", "measurementConditionSource", "measurementConditionBeamsplitter", "measurementConditionDetector", "measurementConditionLaserpower", "measurementConditionExposuretime", "measurementConditionLens", "measurementTechniqueSersChip", "measurementTechniqueSersNanoparticles", "measurementTechniqueSersPapers", "measurementTechniqueSersOther", "experimentId" FROM "temporary_measurement"`);
        await queryRunner.query(`DROP TABLE "temporary_measurement"`);
    }

}
