import { MigrationInterface, QueryRunner } from "typeorm";

export class Initial1735813270648 implements MigrationInterface {
    name = 'Initial1735813270648'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "technique" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "description" varchar NOT NULL, CONSTRAINT "UQ_f61ae45d7238c195698df9e8c62" UNIQUE ("name"))`);
        await queryRunner.query(`CREATE TABLE "instrument" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "description" varchar NOT NULL, "techniqueId" varchar, "equipmentTypeId" varchar, CONSTRAINT "UQ_efda620b8e7e274a712072e2afb" UNIQUE ("name"))`);
        await queryRunner.query(`CREATE TABLE "equipment_type" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "description" varchar NOT NULL, CONSTRAINT "UQ_ce2b5e7a7ca480169494f39fad5" UNIQUE ("name"))`);
        await queryRunner.query(`CREATE TABLE "measurement" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "spectrumDescription" varchar, "remark" varchar, "raman" json, "create_at" datetime NOT NULL DEFAULT (datetime('now')), "update_at" datetime DEFAULT (datetime('now')), "experimentId" varchar, "attachmentName" varchar NOT NULL, "attachmentSize" integer NOT NULL, "attachmentMimetype" varchar NOT NULL, "attachmentFileext" varchar NOT NULL, CONSTRAINT "UQ_c12a927594123273abdccf6c8c5" UNIQUE ("name"))`);
        await queryRunner.query(`CREATE TABLE "category" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "description" varchar NOT NULL, CONSTRAINT "UQ_23c05c292c439d77b0de816b500" UNIQUE ("name"))`);
        await queryRunner.query(`CREATE TABLE "chemical" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "description" varchar, CONSTRAINT "UQ_b0978d04fd0a03ca93abb0c610a" UNIQUE ("name"))`);
        await queryRunner.query(`CREATE TABLE "form" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "description" varchar NOT NULL, CONSTRAINT "UQ_e2b5265b1797dcc0f22ad187985" UNIQUE ("name"))`);
        await queryRunner.query(`CREATE TABLE "sample" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "description" varchar, "source" varchar, "note" varchar, "attachments" json NOT NULL, "images" json NOT NULL, "create_at" datetime NOT NULL DEFAULT (datetime('now')), "update_at" datetime DEFAULT (datetime('now')), "chemicalId" varchar, "categoryId" varchar, "formId" varchar, "organizationId" varchar, CONSTRAINT "UQ_320800b722fc660e4c2b266c8c3" UNIQUE ("name"))`);
        await queryRunner.query(`CREATE TABLE "organization" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "description" varchar NOT NULL, "contact" varchar NOT NULL, CONSTRAINT "UQ_c21e615583a3ebbb0977452afb0" UNIQUE ("name"))`);
        await queryRunner.query(`CREATE TABLE "experiment" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "createAt" datetime NOT NULL DEFAULT (datetime('now')), "updateAt" datetime DEFAULT (datetime('now')), "userId" varchar, "sampleId" varchar, "organizationId" varchar, "techniqueId" varchar, "instrumentId" varchar, "equipmentTypeId" varchar, CONSTRAINT "UQ_73e916a671816778db4f7ae51a3" UNIQUE ("name"))`);
        await queryRunner.query(`CREATE TABLE "download" ("id" varchar PRIMARY KEY NOT NULL, "create_at" datetime NOT NULL DEFAULT (datetime('now')), "experimentId" varchar, "userId" varchar)`);
        await queryRunner.query(`CREATE TABLE "user" ("id" varchar PRIMARY KEY NOT NULL, "isActive" boolean NOT NULL DEFAULT (0), "name" varchar NOT NULL, "preferredUsername" varchar NOT NULL, "givenName" varchar NOT NULL, "familyName" varchar NOT NULL, "email" varchar, "user" json NOT NULL, "create_at" datetime NOT NULL DEFAULT (datetime('now')), "update_at" datetime DEFAULT (datetime('now')), "organizationId" varchar)`);
        await queryRunner.query(`CREATE TABLE "temporary_instrument" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "description" varchar NOT NULL, "techniqueId" varchar, "equipmentTypeId" varchar, CONSTRAINT "UQ_efda620b8e7e274a712072e2afb" UNIQUE ("name"), CONSTRAINT "FK_bef2514b9129dca013689f6ea23" FOREIGN KEY ("techniqueId") REFERENCES "technique" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_064845caa32df6420c2324563ee" FOREIGN KEY ("equipmentTypeId") REFERENCES "equipment_type" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_instrument"("id", "name", "description", "techniqueId", "equipmentTypeId") SELECT "id", "name", "description", "techniqueId", "equipmentTypeId" FROM "instrument"`);
        await queryRunner.query(`DROP TABLE "instrument"`);
        await queryRunner.query(`ALTER TABLE "temporary_instrument" RENAME TO "instrument"`);
        await queryRunner.query(`CREATE TABLE "temporary_measurement" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "spectrumDescription" varchar, "remark" varchar, "raman" json, "create_at" datetime NOT NULL DEFAULT (datetime('now')), "update_at" datetime DEFAULT (datetime('now')), "experimentId" varchar, "attachmentName" varchar NOT NULL, "attachmentSize" integer NOT NULL, "attachmentMimetype" varchar NOT NULL, "attachmentFileext" varchar NOT NULL, CONSTRAINT "UQ_c12a927594123273abdccf6c8c5" UNIQUE ("name"), CONSTRAINT "FK_6b6e4936818d76b783b18ff5ac6" FOREIGN KEY ("experimentId") REFERENCES "experiment" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_measurement"("id", "name", "spectrumDescription", "remark", "raman", "create_at", "update_at", "experimentId", "attachmentName", "attachmentSize", "attachmentMimetype", "attachmentFileext") SELECT "id", "name", "spectrumDescription", "remark", "raman", "create_at", "update_at", "experimentId", "attachmentName", "attachmentSize", "attachmentMimetype", "attachmentFileext" FROM "measurement"`);
        await queryRunner.query(`DROP TABLE "measurement"`);
        await queryRunner.query(`ALTER TABLE "temporary_measurement" RENAME TO "measurement"`);
        await queryRunner.query(`CREATE TABLE "temporary_sample" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "description" varchar, "source" varchar, "note" varchar, "attachments" json NOT NULL, "images" json NOT NULL, "create_at" datetime NOT NULL DEFAULT (datetime('now')), "update_at" datetime DEFAULT (datetime('now')), "chemicalId" varchar, "categoryId" varchar, "formId" varchar, "organizationId" varchar, CONSTRAINT "UQ_320800b722fc660e4c2b266c8c3" UNIQUE ("name"), CONSTRAINT "FK_460349e27a26afd588e6154f457" FOREIGN KEY ("chemicalId") REFERENCES "chemical" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_885ee312ba08566765412f5c246" FOREIGN KEY ("categoryId") REFERENCES "category" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_9424e423b6997d95cffcb149a69" FOREIGN KEY ("formId") REFERENCES "form" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_9855ae6df5fcd0db02a2eb33104" FOREIGN KEY ("organizationId") REFERENCES "organization" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_sample"("id", "name", "description", "source", "note", "attachments", "images", "create_at", "update_at", "chemicalId", "categoryId", "formId", "organizationId") SELECT "id", "name", "description", "source", "note", "attachments", "images", "create_at", "update_at", "chemicalId", "categoryId", "formId", "organizationId" FROM "sample"`);
        await queryRunner.query(`DROP TABLE "sample"`);
        await queryRunner.query(`ALTER TABLE "temporary_sample" RENAME TO "sample"`);
        await queryRunner.query(`CREATE TABLE "temporary_experiment" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "createAt" datetime NOT NULL DEFAULT (datetime('now')), "updateAt" datetime DEFAULT (datetime('now')), "userId" varchar, "sampleId" varchar, "organizationId" varchar, "techniqueId" varchar, "instrumentId" varchar, "equipmentTypeId" varchar, CONSTRAINT "UQ_73e916a671816778db4f7ae51a3" UNIQUE ("name"), CONSTRAINT "FK_efd004fa410567831df8dd764fb" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_b773f55f3d5afe549e96ddc2915" FOREIGN KEY ("sampleId") REFERENCES "sample" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_0426779bd58d26cbe832c9af800" FOREIGN KEY ("organizationId") REFERENCES "organization" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_a968dced2748a865538bcbfae7c" FOREIGN KEY ("techniqueId") REFERENCES "technique" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_912f3f19494e80b6cb91dbc9bf2" FOREIGN KEY ("instrumentId") REFERENCES "instrument" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_3c092842ef313b1dc4ad99c91a3" FOREIGN KEY ("equipmentTypeId") REFERENCES "equipment_type" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_experiment"("id", "name", "createAt", "updateAt", "userId", "sampleId", "organizationId", "techniqueId", "instrumentId", "equipmentTypeId") SELECT "id", "name", "createAt", "updateAt", "userId", "sampleId", "organizationId", "techniqueId", "instrumentId", "equipmentTypeId" FROM "experiment"`);
        await queryRunner.query(`DROP TABLE "experiment"`);
        await queryRunner.query(`ALTER TABLE "temporary_experiment" RENAME TO "experiment"`);
        await queryRunner.query(`CREATE TABLE "temporary_download" ("id" varchar PRIMARY KEY NOT NULL, "create_at" datetime NOT NULL DEFAULT (datetime('now')), "experimentId" varchar, "userId" varchar, CONSTRAINT "FK_ccb403e6acb0b40c7740af652cc" FOREIGN KEY ("experimentId") REFERENCES "experiment" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_9d13a8323fab9297788961ec6cc" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_download"("id", "create_at", "experimentId", "userId") SELECT "id", "create_at", "experimentId", "userId" FROM "download"`);
        await queryRunner.query(`DROP TABLE "download"`);
        await queryRunner.query(`ALTER TABLE "temporary_download" RENAME TO "download"`);
        await queryRunner.query(`CREATE TABLE "temporary_user" ("id" varchar PRIMARY KEY NOT NULL, "isActive" boolean NOT NULL DEFAULT (0), "name" varchar NOT NULL, "preferredUsername" varchar NOT NULL, "givenName" varchar NOT NULL, "familyName" varchar NOT NULL, "email" varchar, "user" json NOT NULL, "create_at" datetime NOT NULL DEFAULT (datetime('now')), "update_at" datetime DEFAULT (datetime('now')), "organizationId" varchar, CONSTRAINT "FK_dfda472c0af7812401e592b6a61" FOREIGN KEY ("organizationId") REFERENCES "organization" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_user"("id", "isActive", "name", "preferredUsername", "givenName", "familyName", "email", "user", "create_at", "update_at", "organizationId") SELECT "id", "isActive", "name", "preferredUsername", "givenName", "familyName", "email", "user", "create_at", "update_at", "organizationId" FROM "user"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`ALTER TABLE "temporary_user" RENAME TO "user"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user" RENAME TO "temporary_user"`);
        await queryRunner.query(`CREATE TABLE "user" ("id" varchar PRIMARY KEY NOT NULL, "isActive" boolean NOT NULL DEFAULT (0), "name" varchar NOT NULL, "preferredUsername" varchar NOT NULL, "givenName" varchar NOT NULL, "familyName" varchar NOT NULL, "email" varchar, "user" json NOT NULL, "create_at" datetime NOT NULL DEFAULT (datetime('now')), "update_at" datetime DEFAULT (datetime('now')), "organizationId" varchar)`);
        await queryRunner.query(`INSERT INTO "user"("id", "isActive", "name", "preferredUsername", "givenName", "familyName", "email", "user", "create_at", "update_at", "organizationId") SELECT "id", "isActive", "name", "preferredUsername", "givenName", "familyName", "email", "user", "create_at", "update_at", "organizationId" FROM "temporary_user"`);
        await queryRunner.query(`DROP TABLE "temporary_user"`);
        await queryRunner.query(`ALTER TABLE "download" RENAME TO "temporary_download"`);
        await queryRunner.query(`CREATE TABLE "download" ("id" varchar PRIMARY KEY NOT NULL, "create_at" datetime NOT NULL DEFAULT (datetime('now')), "experimentId" varchar, "userId" varchar)`);
        await queryRunner.query(`INSERT INTO "download"("id", "create_at", "experimentId", "userId") SELECT "id", "create_at", "experimentId", "userId" FROM "temporary_download"`);
        await queryRunner.query(`DROP TABLE "temporary_download"`);
        await queryRunner.query(`ALTER TABLE "experiment" RENAME TO "temporary_experiment"`);
        await queryRunner.query(`CREATE TABLE "experiment" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "createAt" datetime NOT NULL DEFAULT (datetime('now')), "updateAt" datetime DEFAULT (datetime('now')), "userId" varchar, "sampleId" varchar, "organizationId" varchar, "techniqueId" varchar, "instrumentId" varchar, "equipmentTypeId" varchar, CONSTRAINT "UQ_73e916a671816778db4f7ae51a3" UNIQUE ("name"))`);
        await queryRunner.query(`INSERT INTO "experiment"("id", "name", "createAt", "updateAt", "userId", "sampleId", "organizationId", "techniqueId", "instrumentId", "equipmentTypeId") SELECT "id", "name", "createAt", "updateAt", "userId", "sampleId", "organizationId", "techniqueId", "instrumentId", "equipmentTypeId" FROM "temporary_experiment"`);
        await queryRunner.query(`DROP TABLE "temporary_experiment"`);
        await queryRunner.query(`ALTER TABLE "sample" RENAME TO "temporary_sample"`);
        await queryRunner.query(`CREATE TABLE "sample" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "description" varchar, "source" varchar, "note" varchar, "attachments" json NOT NULL, "images" json NOT NULL, "create_at" datetime NOT NULL DEFAULT (datetime('now')), "update_at" datetime DEFAULT (datetime('now')), "chemicalId" varchar, "categoryId" varchar, "formId" varchar, "organizationId" varchar, CONSTRAINT "UQ_320800b722fc660e4c2b266c8c3" UNIQUE ("name"))`);
        await queryRunner.query(`INSERT INTO "sample"("id", "name", "description", "source", "note", "attachments", "images", "create_at", "update_at", "chemicalId", "categoryId", "formId", "organizationId") SELECT "id", "name", "description", "source", "note", "attachments", "images", "create_at", "update_at", "chemicalId", "categoryId", "formId", "organizationId" FROM "temporary_sample"`);
        await queryRunner.query(`DROP TABLE "temporary_sample"`);
        await queryRunner.query(`ALTER TABLE "measurement" RENAME TO "temporary_measurement"`);
        await queryRunner.query(`CREATE TABLE "measurement" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "spectrumDescription" varchar, "remark" varchar, "raman" json, "create_at" datetime NOT NULL DEFAULT (datetime('now')), "update_at" datetime DEFAULT (datetime('now')), "experimentId" varchar, "attachmentName" varchar NOT NULL, "attachmentSize" integer NOT NULL, "attachmentMimetype" varchar NOT NULL, "attachmentFileext" varchar NOT NULL, CONSTRAINT "UQ_c12a927594123273abdccf6c8c5" UNIQUE ("name"))`);
        await queryRunner.query(`INSERT INTO "measurement"("id", "name", "spectrumDescription", "remark", "raman", "create_at", "update_at", "experimentId", "attachmentName", "attachmentSize", "attachmentMimetype", "attachmentFileext") SELECT "id", "name", "spectrumDescription", "remark", "raman", "create_at", "update_at", "experimentId", "attachmentName", "attachmentSize", "attachmentMimetype", "attachmentFileext" FROM "temporary_measurement"`);
        await queryRunner.query(`DROP TABLE "temporary_measurement"`);
        await queryRunner.query(`ALTER TABLE "instrument" RENAME TO "temporary_instrument"`);
        await queryRunner.query(`CREATE TABLE "instrument" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "description" varchar NOT NULL, "techniqueId" varchar, "equipmentTypeId" varchar, CONSTRAINT "UQ_efda620b8e7e274a712072e2afb" UNIQUE ("name"))`);
        await queryRunner.query(`INSERT INTO "instrument"("id", "name", "description", "techniqueId", "equipmentTypeId") SELECT "id", "name", "description", "techniqueId", "equipmentTypeId" FROM "temporary_instrument"`);
        await queryRunner.query(`DROP TABLE "temporary_instrument"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TABLE "download"`);
        await queryRunner.query(`DROP TABLE "experiment"`);
        await queryRunner.query(`DROP TABLE "organization"`);
        await queryRunner.query(`DROP TABLE "sample"`);
        await queryRunner.query(`DROP TABLE "form"`);
        await queryRunner.query(`DROP TABLE "chemical"`);
        await queryRunner.query(`DROP TABLE "category"`);
        await queryRunner.query(`DROP TABLE "measurement"`);
        await queryRunner.query(`DROP TABLE "equipment_type"`);
        await queryRunner.query(`DROP TABLE "instrument"`);
        await queryRunner.query(`DROP TABLE "technique"`);
    }

}
